# Generated by Django 4.1.2 on 2022-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Addresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=6, verbose_name="Индекс"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="Страна"),
                ),
                (
                    "federal_district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Федеральный округ"
                    ),
                ),
                (
                    "region_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Тип региона"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Регион"),
                ),
                (
                    "area_type",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Тип местности"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Местность"
                    ),
                ),
                (
                    "city_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Тип города"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Тип поселка"
                    ),
                ),
                (
                    "settlement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Поселок"
                    ),
                ),
                (
                    "kladr_id",
                    models.IntegerField(verbose_name="Идентификатор в системе КЛАДР"),
                ),
                (
                    "fias_id",
                    models.UUIDField(verbose_name="Идентификатор в системе ФИАС"),
                ),
                (
                    "fias_level",
                    models.IntegerField(verbose_name="Уровень в системе ФИАС"),
                ),
                ("capital_marker", models.IntegerField(verbose_name="Метка столицы")),
                (
                    "okato",
                    models.CharField(blank=True, max_length=11, verbose_name="ОКАТО"),
                ),
                (
                    "oktmo",
                    models.CharField(blank=True, max_length=11, verbose_name="ОКТМО"),
                ),
                ("tax_office", models.IntegerField(verbose_name="Номер налоговой")),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="Часовой пояс"
                    ),
                ),
                (
                    "geo_lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Широта"
                    ),
                ),
                (
                    "geo_lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                ("population", models.IntegerField(verbose_name="Население")),
                ("foundation_year", models.IntegerField(verbose_name="Год основания")),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
    ]
