# Generated by Django 4.1.2 on 2022-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="geo_lat",
            field=models.DecimalField(
                db_index=True, decimal_places=6, max_digits=9, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="addresses",
            name="geo_lon",
            field=models.DecimalField(
                db_index=True, decimal_places=6, max_digits=9, verbose_name="Долгота"
            ),
        ),
    ]
